### PR TITLE
Better formatting and fixing code inside code block

### PR DESCRIPTION
**Pull request by romixch**
More fixes:
- When creating a messaging invitation there are two mandatory fields: **to** and **operationId**
- The exampels were in broken formatting so you couldn't read nor use it.

### CODE REVIEW

**Comment by JohnAustin-MSFT** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/UCWA/startMessaging_ref.md](https://github.com/romixch/skype-docs/blob/master/Skype/UCWA/startMessaging_ref.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C14%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201802141708314956-410%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RFp7sSgPWai7PF8NvY9n9WZ%2ByZ%2Fb6DPf2NiqRFdm1LU%3D&st=2018-02-14T17%3A04%3A16Z&se=2018-03-17T17%3A09%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JohnAustin-MSFT** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/UCWA/startMessaging_ref.md](https://github.com/romixch/skype-docs/blob/master/Skype/UCWA/startMessaging_ref.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C14%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201802141724479563-410%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lauU7evERkohknmcfwR7sGWMtJkwFHeEls1hBwuFRDY%3D&st=2018-02-14T17%3A20%3A31Z&se=2018-03-17T17%3A25%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JohnAustin-MSFT** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/UCWA/startMessaging2_ref.md](https://github.com/romixch/skype-docs/blob/master/Skype/UCWA/startMessaging2_ref.md) | :white_check_mark:Succeeded | |
[Skype/UCWA/startMessaging_ref.md](https://github.com/romixch/skype-docs/blob/master/Skype/UCWA/startMessaging_ref.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C15%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201802150731499381-410%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UclCEg3RKZ9iIxUu7sUQ4OUR6gcvDubnC%2BrItRyVOlM%3D&st=2018-02-15T07%3A27%3A32Z&se=2018-03-18T07%3A32%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
@romixch This is an old PR, so closing. If you still think these changes need to be made, please file a new PR. Thanks.

**Pull request closed without merging**
