### PR TITLE
Leaders and attendees of MyOnlineMeeting requirements

### PR DESCRIPTION
**Pull request by baywet**
Adding information around the requirements for leaders and attendees.
The users to be added there have to be part of the organization or otherwise you'll get an error when submitting the data.
Fixed a typo as well

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/UCWA/myOnlineMeetings_ref.md](https://github.com/baywet/skype-docs/blob/patch-1/Skype/UCWA/myOnlineMeetings_ref.md) | :warning:Warning | | [Details](#user-content-Skype%2FUCWA%2FmyOnlineMeetings_ref.md)

<a name="Skype%2FUCWA%2FmyOnlineMeetings_ref.md"></a>
### [Skype/UCWA/myOnlineMeetings_ref.md](https://github.com/baywet/skype-docs/blob/patch-1/Skype/UCWA/myOnlineMeetings_ref.md)
 - **Line 359**: **[Warning]** Invalid file link:(~/UCWA/OnlineMeetingResource_ref.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C12%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201707121402204010-341%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by baywet** [comment]
More context for this Pull Request https://stackoverflow.com/questions/44709274/ucwa-myonlinemeeting-attendees-requirements-external-attendees/45060058

**Comment by JohnAustin-MSFT** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/UCWA/myOnlineMeetings_ref.md](https://github.com/baywet/skype-docs/blob/patch-1/Skype/UCWA/myOnlineMeetings_ref.md) | :warning:Warning | | [Details](#user-content-Skype%2FUCWA%2FmyOnlineMeetings_ref.md)

<a name="Skype%2FUCWA%2FmyOnlineMeetings_ref.md"></a>
### [Skype/UCWA/myOnlineMeetings_ref.md](https://github.com/baywet/skype-docs/blob/patch-1/Skype/UCWA/myOnlineMeetings_ref.md)
 - **Line 359**: **[Warning]** Invalid file link:(~/UCWA/OnlineMeetingResource_ref.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C25%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201801252142294787-341%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hXSqY4Br3a9i9%2BHDJbOBH1jYbdcB1Z1TeFXuv6wPykU%3D&st=2018-01-25T21%3A38%3A10Z&se=2018-02-25T21%3A43%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JohnAustin-MSFT** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/UCWA/myOnlineMeetings_ref.md](https://github.com/baywet/skype-docs/blob/patch-1/Skype/UCWA/myOnlineMeetings_ref.md) | :warning:Warning | | [Details](#user-content-Skype%2FUCWA%2FmyOnlineMeetings_ref.md)

<a name="Skype%2FUCWA%2FmyOnlineMeetings_ref.md"></a>
### [Skype/UCWA/myOnlineMeetings_ref.md](https://github.com/baywet/skype-docs/blob/patch-1/Skype/UCWA/myOnlineMeetings_ref.md)
 - **Line 359**: **[Warning]** Invalid file link:(~/UCWA/OnlineMeetingResource_ref.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C25%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201801252144280142-341%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XpYOf48HsYPBvpp2hLxBtT%2B%2Fp5hgfp3BnXrn59adls8%3D&st=2018-01-25T21%3A40%3A12Z&se=2018-02-25T21%3A45%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by baywet** [comment]
@davnewman it took time but thanks for merging!

**Pull request merged**
