### PR TITLE
tiny fix base on feedback

### PR DESCRIPTION
**Pull request by jichemicrosoft**

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C16%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201703161722145825-223%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C17%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201703172150039577-223%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jichemicrosoft** [comment]
add bug fix : AccessLevel  is not passed

**Comment by saldana** [comment]
### :x: Validation status: errors


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C17%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201703172300099453-223%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/Trusted-Application-API/SDK/ClientModel/HttpTransport/RestfulClient.cs](https://github.com/jichemicrosoft/skype-docs/blob/master/Skype/Trusted-Application-API/SDK/ClientModel/HttpTransport/RestfulClient.cs) | :white_check_mark:Succeeded | |
[Skype/Trusted-Application-API/SDK/ClientModel/Interfaces/Resources.cs](https://github.com/jichemicrosoft/skype-docs/blob/master/Skype/Trusted-Application-API/SDK/ClientModel/Interfaces/Resources.cs) | :white_check_mark:Succeeded | |
[Skype/Trusted-Application-API/SDK/ClientModel/Resources/AdhocMeeting.cs](https://github.com/jichemicrosoft/skype-docs/blob/master/Skype/Trusted-Application-API/SDK/ClientModel/Resources/AdhocMeeting.cs) | :white_check_mark:Succeeded | |
[Skype/Trusted-Application-API/SDK/ClientModel/Resources/Input.cs](https://github.com/jichemicrosoft/skype-docs/blob/master/Skype/Trusted-Application-API/SDK/ClientModel/Resources/Input.cs) | :white_check_mark:Succeeded | |
[Skype/Trusted-Application-API/SDK/ClientModel/Resources/Invitation.cs](https://github.com/jichemicrosoft/skype-docs/blob/master/Skype/Trusted-Application-API/SDK/ClientModel/Resources/Invitation.cs) | :white_check_mark:Succeeded | |
[Skype/Trusted-Application-API/SDK/Tests/ClientModel/Invitation.cs](https://github.com/jichemicrosoft/skype-docs/blob/master/Skype/Trusted-Application-API/SDK/Tests/ClientModel/Invitation.cs) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C17%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201703172303027036-223%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
