### PR TITLE
Sethli/update auth meeting join sample

### PR DESCRIPTION
**Pull request by slifland37**
Anon meeting join sample will not actually be viewable or deployed yet since they aren't necessarily suitable for the public since they all talk to the same UCAP app and must be hosted locally.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C11%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201702110126551923-179%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ajkher** [comment]
In file AzureAD/index.ts, we can stil keep the mdFileUrl to point to PTAuthAzureAD.md for consistency, as we've already set up a redirect URL there.

**Comment by ajkher** [comment]
Move video-utlis to /Samples/utils/video-utils instead of Samples/Video/video-utils?

**Comment by ajkher** [comment]
Factoring out video-utils is great stuff! (y)

**Comment by ajkher** [comment]
I see what you said with the MDFIleRenderer on our end not rendering the reirected MD but the source MD as is. I saw on MSDN too, if we are to redirected from under Programming Tasks/Authentication/Azure AD, the navigation messes up. We may keep 2 copies of the same file for now (and call the one under Samples 'PTAuthAzureAD'). Maybe later, we can edit the one under Programming Tasks to include only certain details with a link to 'DevelopWebSDKappsForSfBOnline' under Additional Resources.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C15%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201702150047200037-179%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C15%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201702150052507713-179%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
