### PR TITLE
Update in-call-qoe-algorithm-and-throttling.md

### PR DESCRIPTION
**Pull request by Ariantor**

### CODE REVIEW

**Comment by Linda-Editor** [comment]
Docs Build status updates of commit _[81f17fe](https://github.com/Ariantor/skype-docs/commits/81f17fe7e133bc325be4f64bf96fb3434bcae009)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/SDN/articles/in-call-qoe-algorithm-and-throttling.md](https://github.com/Ariantor/skype-docs/blob/patch-46/Skype/SDN/articles/in-call-qoe-algorithm-and-throttling.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C9%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201908091600150771-564%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r1KMpjZJyho6EWdqBXil40Oe1cBVAR%2FbUhV1lw09G30%3D&st=2019-08-09T15%3A56%3A25Z&se=2019-09-09T16%3A01%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@Ariantor Please resolve the conflict so I can merge. Thanks, lindalu

**Comment by Linda-Editor** [comment]
Docs Build status updates of commit _[181cbc4](https://github.com/Ariantor/skype-docs/commits/181cbc4432bc66fc19c50edc81fa65a95bab4606)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/SDN/articles/in-call-qoe-algorithm-and-throttling.md](https://github.com/Ariantor/skype-docs/blob/patch-46/Skype/SDN/articles/in-call-qoe-algorithm-and-throttling.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C14%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201908141847567912-564%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HSlpeUh1ajaG3tH0XqhtNClGP%2FITlBhuOubxOFZXVoo%3D&st=2019-08-14T18%3A44%3A05Z&se=2019-09-14T18%3A49%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Ariantor** [comment]
Hi Linda – have you completed all the commit that I submitted?

Thanks,
Ari.-

**Comment by Linda-Editor** [comment]
@Ariantor Yes. Changes should be live in about 30 minutes if not sooner. Thanks for your help.

**Comment by Ariantor** [comment]
Thanks Linda for your help.
I made more changes and this now, I have submitted the “Proposed Changes” and have not created a Pull Request.

However, I do not see all the changes I have made. Could you direct me to the interface where I can choose the changes I have made and submit the Pull Request?

Thanks,
Ari.-

**Comment by Linda-Editor** [comment]
@Ariantor In your fork, go to the root page (usually by clicking skype-docs in the breadcrumb path). In your fork, just above the table of contents, you'll see a button that says **New pull request**. Under **Compare changes**, set **base** to master, and **compare** to your fork, and then submit the PR. You can find more information here: https://github.com/OfficeDev/skype-docs/blob/master/CONTRIBUTING.md

Hope this helps.

**Comment by Ariantor** [comment]
Thanks Linda. I am just slow, sorry. For the life of me, I could not see how you can “bulk” submit the changes. I cannot find a way to select multiple changes I have made and submit them in bulk. I might miss some steps in your instructions below.

Thank you again for your help!

**Comment by Linda-Editor** [comment]
@Ariantor Can you send me the link to your fork where you've made the changes? For example, instead of OfficeDev, it will have your fork name in the URL: https://github.com/OfficeDev/skype-docs/

**Comment by Ariantor** [comment]
Thanks Linda. The fork names are Patch-57, Patch-58 and so on until Patch-65.
I am adding Rick as well since I will be leaving for vacation starting tomorrow. Rick can help make changes. If he does not have permission, please kindly help as well to provide proper access for him.

I hope Rick does not have to do anything and the pull request can be made and the changes can be completed.

Thanks again for your help,
Ari.-

**Comment by lindalu-MSFT** [comment]
@Ariantor The step you're missing is that you need to create a new working branch and then clone the repo. Then, you work locally in your branch. When you go to merge your changes, all your changes go into one PR. What you're doing now creates a new separate branch for each patch. Please read up on this before your next bulk update! We want all changes in one PR. It's way to time consuming to do this individually. It took me over several days to merge the last update you did. Both Linda and I can help if you have questions.

**Comment by lindalu-MSFT** [comment]
p.s. @Linda-Editor Are we ready to merge to live in this repo?

**Comment by Ariantor** [comment]
Thanks Linda. I will do more reading. I must say this is all new to me and I do not have a formal training how the whole system works.

**Comment by Linda-Editor** [comment]
@lindalu-MSFT The prior PRs that you merged to master were all merged to live already. He just needs to get his new changes into the one PR. Thanks for your help.

**Comment by Ariantor** [comment]
Thanks Linda. Please add Rick on the subsequent replies since I will be out starting tomorrow.

**Comment by Ariantor** [comment]
Hi Linda – just want to follow up since I just came back from vacation.

Hope all is well.
Thank you again for your help. I am still not clear how to do “bulk” pull requests. Maybe it is just me, but I find the UI very confusing….

Ari.-

From: Ari Ridwan
Sent: Thursday, August 22, 2019 4:23 PM
To: OfficeDev/skype-docs <reply@reply.github.com>; OfficeDev/skype-docs <skype-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Rick Varvel <rickva@microsoft.com>
Subject: RE: [OfficeDev/skype-docs] Update in-call-qoe-algorithm-and-throttling.md (#564)

Thanks Linda. Please add Rick on the subsequent replies since I will be out starting tomorrow.

**Comment by lindalu-MSFT** [comment]
@Ariantor Hi, do you use Teams or another app where I can share my screen and show you in person? I think it will make more sense!

**Comment by Ariantor** [comment]
Thank you Linda. Yes, I use Teams, that would be great. :)  Should I reach out to you in Teams?

**Comment by lindalu-MSFT** [comment]
@Ariantor Sure, ping me on Teams and I'll give you a quick demo what you need to do.

**Pull request merged**
