### PR TITLE
Update configuring-incallqoe-messages.md

### PR DESCRIPTION
**Pull request by Ariantor**

### CODE REVIEW

**Comment by Linda-Editor** [comment]
Docs Build status updates of commit _[13249ee](https://github.com/Ariantor/skype-docs/commits/13249eeb2a92bfe50f1bf1de02b7b492d4fcac48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/SDN/articles/configuring-incallqoe-messages.md](https://github.com/Ariantor/skype-docs/blob/patch-56/Skype/SDN/articles/configuring-incallqoe-messages.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C9%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201908091613375088-574%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Cdkko9bOHb1Lbvuisar4UkCSXZbTem4hmjeINMDHIP8%3D&st=2019-08-09T16%3A09%3A49Z&se=2019-09-09T16%3A14%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
@Ariantor Thanks for making these updates; however, they could have all been done in one pull request. :-(  In the future, if you have changes like this that are basically the same change across docs, please submit them in one PR, not individual PRs.

**Comment by Ariantor** [comment]
Thanks Linda. Any better way of doing find and replace quickly?  I had to manually go to each link and make same changes.

________________________________

**Comment by Linda-Editor** [comment]
@Ariantor You can clone the repo, make changes in Visual Studio Code or another editor, and push those changes to your branch. Then you can create one pull request to merge them to master. FYI - I'm no longer at Microsoft, so will let the editor know these pull requests are waiting.

@lindalu-MSFT Hi LindaLu, can you process these PRs and push them live? Thanks...

**Comment by Ariantor** [comment]
Hi Linda,
I still do not see my changes, are they still in progress?

Thanks,
Ari.-

**Comment by Linda-Editor** [comment]
@Ariantor A few have been pushed live, but because there are over 50 separate pull requests, they will take a lot of time to merge. The other editor will get to them as she has time.

**Comment by Ariantor** [comment]
Thanks Linda. I will submit one pull next time, in the meantime, is there anything I can do to accelerate the process?

**Pull request merged**
