### PR TITLE
UCWA auth request `response_type` fixed to `token`

### PR DESCRIPTION
**Pull request by AlmogCohen**
The `response_type` of the first OAuth request was incorrect. You can check it out yourself. I was wasting on it a lot of time...
With the old `id_token` response_type, only the `id_token` is returned. Now, with `token` resposne_type, the actual `access_token` is returned. Some of the response fields as described here also missing but I'm not sure if this is only my case.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/UCWA/AuthenticationUsingAzureAD.md](https://github.com/AlmogCohen/skype-docs/blob/patch-1/Skype/UCWA/AuthenticationUsingAzureAD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C2%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201707022121171474-330%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlmogCohen** [comment]
anybody?

**Comment by AlmogCohen** [comment]
Quick responses here

**Comment by Linda-Editor** [comment]
@AlmogCohen This is an old PR, so closing. If you still think these changes need to be made, please file a new PR. Thanks.

**Pull request closed without merging**
