### PR TITLE
Removed conversation history section from Skype Web SDK and UCWA TOC

### PR DESCRIPTION
**Pull request by AasveenKaur**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/TOC.md](https://github.com/OfficeDev/skype-docs/blob/Aasveen/RemoveConversationHistory/Skype/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C13%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201706131650201658-313%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/TOC.md](https://github.com/OfficeDev/skype-docs/blob/Aasveen/RemoveConversationHistory/Skype/TOC.md) | :white_check_mark:Succeeded | |
[Skype/UCWA/WhatsNewInUCWA2_0.md](https://github.com/OfficeDev/skype-docs/blob/Aasveen/RemoveConversationHistory/Skype/UCWA/WhatsNewInUCWA2_0.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C13%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201706131652415625-313%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JohnAustin-MSFT** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Skype/TOC.md](https://github.com/OfficeDev/skype-docs/blob/Aasveen/RemoveConversationHistory/Skype/TOC.md) | :white_check_mark:Succeeded | |
[Skype/UCWA/WhatsNewInUCWA2_0.md](https://github.com/OfficeDev/skype-docs/blob/Aasveen/RemoveConversationHistory/Skype/UCWA/WhatsNewInUCWA2_0.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C25%5C5315e434-bbfc-97f8-0e56-7036cb0b5e04%5CPullRequest%5C201801252226519932-313%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=frkL0X8lVPDP%2F2zCxyWjRaID5EM991xvklC88POEd6Q%3D&st=2018-01-25T22%3A22%3A43Z&se=2018-02-25T22%3A27%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
@AasveenKaur This is an old PR, so closing. If you still think these changes need to be made, please file a new PR. Thanks.

**Pull request closed without merging**
