### PR TITLE
Merge master into live

### PR DESCRIPTION
**Pull request by richardtaylorrt**

### CODE REVIEW

**Comment by dheran** [comment]
@richardtaylorrt  Hi,

Where can I download sdk for Android and iOS. MSDN doc page doesn't seems to work properly.

**Comment by richardtaylorrt** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=51962
https://www.microsoft.com/en-us/download/details.aspx?id=51961

Do the docs not work for you?
https://msdn.microsoft.com/en-us/skype/appsdk/skypeappsdk
https://msdn.microsoft.com/en-us/skype/appsdk/download

**Comment by dheran** [comment]
@richardtaylorrt thanks for the links. Now I can able to download.
Do you have any idea about when stable version about to release?

**Comment by srividhc** [comment]
There is preview update today

**Comment by dheran** [comment]
@srividhc Thanks, for the update. I've checked now, It's still 5.0.1. Today (you) mean IST?
Any clue about stable release? 
Any way to receive updates about latest release of sdk's?

**Comment by srividhc** [comment]
The update is 0.5.1. 
What has been your concern with the release. (I am trying to understand what do you mean by stable release). 

http://dev.office.com/skype/get-involved

Please join the program to get announcements

**Comment by dheran** [comment]
Because, we're planning for production. and little scared to use beta stage library in production application.

I've other clarification also,
1) How the licencing works. (any user limits)?
2) Is it mandatory to register the skype user first?
3) If 2 is mandatory, can we manage users dynamically?
4) Can we generate meeting link without registering a user?

**Comment by dheran** [comment]
@srividhc in addition to above queries,
5)  is there any max limit for creating meetings against single user?

**Pull request merged**
